# Generated by Django 5.0.7 on 2024-07-21 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='изображение')),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='дата публикации')),
                ('is_pay', models.BooleanField(default=False, verbose_name='платная публикация')),
                ('is_active', models.BooleanField(default=True, verbose_name='скрыть/показывать')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
