# Generated by Django 5.0.7 on 2024-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nickname_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=200, unique=True, verbose_name='псевдоним'),
        ),
    ]
